name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  backend:
    name: Backend - ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Roadmap
            solution: code/backend/AssessmentMicroservices.slnx
          - name: Custom challenge
            solution: code/custom-challenge/backend/CustomChallenge.slnx

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Restore
        run: dotnet restore "${{ matrix.solution }}"

      - name: Build
        run: dotnet build "${{ matrix.solution }}" --no-restore

      - name: Test
        run: dotnet test "${{ matrix.solution }}" --no-build --no-restore

  frontend:
    name: Frontend - ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Roadmap Angular
            working-directory: code/frontend/angular
            test: true
          - name: Roadmap React
            working-directory: code/frontend/react
            test: false
          - name: Custom challenge Angular
            working-directory: code/custom-challenge/frontend/angular
            test: true
          - name: Custom challenge React
            working-directory: code/custom-challenge/frontend/react
            test: false

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install packages
        run: npm install
        working-directory: ${{ matrix.working-directory }}

      - name: Build
        run: npm run build
        working-directory: ${{ matrix.working-directory }}

      - name: Test
        if: ${{ matrix.test }}
        run: npm test
        working-directory: ${{ matrix.working-directory }}
